### ISSUE TITLE
Sending (printing) more than 17 or so data bytes is unreliable

### ISSUE THREAD

**Issue by briggsm** [adafruit/Adafruit_BluefruitLE_nRF51#5]
Running _bleuart_datamode_ example on Arduino w/ nRF51822 attached. And using either **nRF UART** app or **Bluefruit LE** app (I'm using iOS versions of these apps), if I type "abcdefghijklmnopqrst" (20 bytes) in the Serial Monitor's input field and Send it, sometimes it goes through immediately, and other times it hangs for about 2-3 seconds then I see "qrst" in the phone app.

If I send "abcdefghijklmnopqrs" (19 bytes), same thing - sometimes works immediately, other times 2-3 second delay then "qrs" show up in phone app.

The fewer the bytes, the more often is seems to work (maybe a timing issue, or timeout issue?).  I've had pretty good luck with 16 bytes and less, but I don't feel that I can trust that 16 bytes will ALWAYS work...

The above is a bug, I believe, but I also have some clarifying questions:

I read that there's a 20-byte limit. Does this mean we can never send more than 20 bytes at a time in our Android code? And same question from the other end - should we only expect a max of 20 bytes from the outside (phone app, for example)?  If we have a 50-byte string, are we responsible for breaking it up, or should that be done in your code?

Thank you for your help & looking into this.

**Comment by microbuilder** [comment]
Please be sure that you are using at least firmware 0.6.7 (the latest), which fixes some FIFO issues around UART.  If you aren't sure which version you have you can see it by using the 'Information' service on your iOS device and looking at the Device Information section.

BLE is limited to 20 bytes in a single BLE packet, but the app will break larger strings up into 20 byte or smaller packets for you automatically, and send multiple packets over the air.  This should be entirely transparent to you.

I'm going to close this issue, though, since this should really be handled in the support forum, and the support staff can't monitor issues here (I'm only seeing this because I'm a dev on this repo).  If updating the firmware doesn't fix this issue for you (I think it will), please repost this question in the Wireless section on the Adafruit support forum with a link to this thread.  Thanks!
